apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: hacbs-test-project-btd6
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-velf-tenant/rhtap-demo-app/hacbs-test-project-btd6@sha256:41d05a63174b0e0ba492df23924de00d969e479f6269ac57029cc72cef328dbb
        name: hacbs-jvm-build-test-project
        resources: {}
status: {}
